server:
  port: 9090

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
#   //Добавил 2 строчки выше
  main:
    web-application-type: reactive
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://backend-resources:9191/api
          predicates:
            Path=/api/**
      default-filters: TokenRelay=
  security:
    oauth2:
      client:
        registration:
#          keycloak:
#            client-id: gateway-client
#            client-secret: nEfPxZ1OZxjFBaMnDQe8vuIQNfpypcz1
#            scope: openid,profile
          backend-gateway-client:
            provider: my-provider
            client-id: backend-gateway-client
            client-secret: nEfPxZ1OZxjFBaMnDQe8vuIQNfpypcz1
            authorization-grant-type: authorization_code
            redirect-uri: "http://backend-gateway-client:9090/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://backend-keycloak-auth:8080/auth/realms/ITM
