version: '4'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: vrd
        MYSQL_USER: andrey
        MYSQL_PASSWORD: 1234
    volumes:
        - ./mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"

volumes:
  db_data:
